name: androidLint

on:
  #push:
  #  branches:
  #    - main
  #    - setup/base
  #    - 'feature/**'
  #  paths-ignore:
  #    - '**/README.*'

  pull_request:
    branches:
      - main
      - setup/base
      - 'feature/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'todo.md'
      - 'docs/**'

  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles(
            'gradle.properties',
            '**/gradle-wrapper.properties',
            '**/*.gradle.kts',
            '**/libs.versions.toml'
            ) }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Output dependencies
        run: ./gradlew dependencies

      - name: Run Inspection
        run: ./gradlew lint --no-daemon

      - name: Upload androidLint reports
        uses: actions/upload-artifact@v4
        with:
          name: androidLint-reports
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Cache Ruby gems
        uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('ci/androidLint/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('ci/androidLint/Gemfile.lock') }}
            ${{ runner.os }}-gems-${{ hashFiles('ci/androidLint/Gemfile') }}
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v6
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/androidLint/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/androidLint/Dangerfile'
          danger_id: 'danger-pr-androidLint'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
