name: androidLint

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/README.*'
      - 'LICENSE'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/README.*'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Inspection
        run: ./gradlew lint

      - name: Upload androidLint reports
        uses: actions/upload-artifact@v4
        with:
          name: androidLint-reports
          path: |
            app/build/reports/lint-results-*.html
            app/build/reports/lint-results-*.xml

      - name: Setup Ruby, JRuby and TruffleRuby
        if: github.event_name == 'pull_request'
        uses: ruby/setup-ruby@v1.213.0
        with:
          ruby-version: '3.3'

      - name: Cache Ruby gems
        uses: actions/cache@v4
        if: github.event_name == 'pull_request'
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: MeilCli/danger-action@v6
        if: github.event_name == 'pull_request'
        with:
          plugins_file: 'ci/androidLint/Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'ci/androidLint/Dangerfile'
          danger_id: 'danger-pr-androidLint'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
