name: coverage

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/README.*'
      - 'LICENSE'

  workflow_dispatch:

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Coverage(Xml)
        run: ./gradlew koverXmlReportDebug
        continue-on-error: true

      - name: Upload coverage reports to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: asabon/AndroidAppSample
